### ISSUE TITLE
iASL download script deprecated.

### ISSUE THREAD

**Issue by afkniladri** [corpnewt/CPUFriendFriend#16]
Developers kindly check the script.

**Comment by corpnewt** [comment]
Are you referring to the download location used for the iasl binary?  If so - that's on my to do list, but shouldn't cause any problems for the time being as it's only being used to compile the resulting SSDT created by CPUFriend's ResourceConverter.sh.  I updated the download links in ACPIRename and SSDTTime as they also need to decompile a wide range of DSDTs.

If that's not what you're referring to though, could you further explain?

-CorpNewt

**Comment by afkniladri** [comment]
The CPUFriendFriend.command script won't download the iasl binary into the scripts folder. I had to manually download it and place it in the folder. Even after updating the python certificate it won't download.

**Comment by afkniladri** [comment]
P.S - The script is working perfectly fine, just the downloader for iasl is causing issue; it gets stuck on black screen.

**Comment by corpnewt** [comment]
Hmmm - interesting.  What version of macOS and Python are you using?  I can test locally today and make sure it can download the binary here - but if you're running an older version of Python, it may be due to that.  IIRC, the Python 2 packaged with macOS (pre-12.3, as Apple no longer ships macOS with Python) lacks certificates to communicate with some websites via urllib (which is what my downloader.py leverages) - and that can cause issues downloading.

You could update Python if you're on an older version - and I can verify here that it works.  I'll be leveraging macOS 12.4 beta 4, and Python 3.10.2 (I believe?) for my tests.

-CorpNewt

**Comment by afkniladri** [comment]
Python ver : 3.9 
Mac OS ver : Monterey 12.3.1

**Comment by corpnewt** [comment]
3.9 should be able to download properly (assuming you've run the InstallCertificates.command in /Applications/Python 3.9), that's odd.  And it just hangs with no output?  Would you mind pasting everything the terminal window outputs when you open CPUFriendFriend.command?

-CorpNewt

**Comment by afkniladri** [comment]
It just get's stuck on downloading. Network is perfectly fine.

**Comment by corpnewt** [comment]
I'll test quick and let you know what happens on my end.

**Comment by corpnewt** [comment]
Yeah - I just verified on my laptop which is running 12.4 beta 4 and Python 3.10.2 - and it was able to download and extract the iasl binary just fine.  You could try with an updated Python version I suppose?  Or re-run the InstallCertificates.command file and try again.

-CorpNewt

**Comment by corpnewt** [comment]
If nothing else - I plan to update the script to check Acidanthera's MaciASL repo for the iasl binary instead of using the bitbucket link - which may or may not alleviate the symptoms you're experiencing.  I would consider a repo change to be more of a band-aid fix than an actual solution though (assuming it even works).  It sounds to me like something is potentially amiss in your python setup.

-CorpNewt

**Comment by afkniladri** [comment]
It worked. Used Python 3.10.2. Keep up the great work. Thanks!

**Comment by corpnewt** [comment]
Glad to hear it!  I'll still switch to the updated repo for the sake of keeping things current at some point today though 👍 

-CorpNewt
